In [3]:
# np.add()
# np.subtract()
# np.multiply()
# np.divide()
# np.mod()
# np.power()
# np.reciprocal()
# np.min()
# np.max()
# np.argmax()
# np.argmin()
# Iteration Array
# np.nditer()
# np.ndenumerate()
# np.concatenate
# np.stack
# slicing and assignment

In [4]:
import numpy as np

In [5]:
# 1d, 2d, 3d, 4d, 
# reshape,shape, size, ndim, type, astype, dtype, 

In [38]:
a = np.array([1,234,456,346])
b = np.array([12,43,574,56])

a + b

array([  13,  277, 1030,  402])

In [40]:
np.add(a,b)

array([  13,  277, 1030,  402])

In [43]:
c = np.array([1,243,46,78])


np.add(a,b,c)

array([  13,  277, 1030,  402])

In [ ]:
# np.add()
# np.subtract()
# np.multiply()
# np.divide()
# np.mod()
# np.power()
# np.reciprocal()

In [47]:
a

array([  1, 234, 456, 346])

In [48]:
b

array([ 12,  43, 574,  56])

In [49]:

np.power(a,b)

array([1, 0, 0, 0])

In [53]:
c = a**b

In [56]:
# c.astype('int64')

In [57]:
a = np.array([1,2,3,4])

b = np.array([2,2,2,2])

a**b

array([ 1,  4,  9, 16])

In [58]:
np.power(a,b)

array([ 1,  4,  9, 16])

In [59]:
a = np.array([1,234,456,346])
b = np.array([12,43,574,56])
a

array([  1, 234, 456, 346])

In [60]:
b

array([ 12,  43, 574,  56])

In [62]:
# 234**43

In [66]:
a = a.astype('int64')
b = b.astype('int64')

In [67]:
a**b

array([                   1,  4664999138234990592,                    0,
       -2233785415175766016], dtype=int64)

In [69]:
d = 456**574

In [70]:
import os

In [71]:
import sys

In [73]:
sys.getsizeof(d)

704

In [74]:
# np.reciprocal()

In [78]:
a = np.array([1,2,4,3,2,5,67])
b = np.array([24,3,5,6,7])


np.reciprocal(a)

array([1, 0, 0, 0, 0, 0, 0])

In [79]:
np.reciprocal([1, 2., 3.33])

array([1.       , 0.5      , 0.3003003])

In [87]:
a = np.array([1,2,4,3,2,5,67],dtype = 'float16')
b = np.array([24,3,5,6,7],dtype = 'float16')


1/a

array([1.     , 0.5    , 0.25   , 0.3333 , 0.5    , 0.2    , 0.01492],
      dtype=float16)

In [88]:
np.reciprocal(a)

array([1.     , 0.5    , 0.25   , 0.3333 , 0.5    , 0.2    , 0.01492],
      dtype=float16)

In [89]:
# np.min()
# np.max()
# np.argmax()
# np.argmin()
# Iteration Array
# np.nditer()
# np.ndenumerate()
# np.concatenate
# np.stack

In [91]:
a = np.arange(1,26,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [92]:
a.ndim

1

In [97]:
a.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [99]:
a = np.random.randint(1,100,(5,5))
a

array([[97, 43, 43, 51, 26],
       [13, 88, 23,  7, 40],
       [49, 73, 33, 78, 45],
       [52, 79, 60, 52, 70],
       [ 8, 23, 65, 58, 16]])

In [100]:
np.min(a)

7

In [101]:
np.max(a)

97

In [103]:
a.min()

7

In [104]:
a.max()

97

In [112]:
max(a.flatten())

97

In [113]:
min(a.flatten())

7

In [114]:
a

array([[97, 43, 43, 51, 26],
       [13, 88, 23,  7, 40],
       [49, 73, 33, 78, 45],
       [52, 79, 60, 52, 70],
       [ 8, 23, 65, 58, 16]])

In [117]:
np.max(a,axis=0)   # column along

array([97, 88, 65, 78, 70])

In [118]:
np.max(a,axis=1)   # row along

array([97, 88, 78, 79, 65])

In [119]:
np.min(a,axis=0)

array([ 8, 23, 23,  7, 16])

In [122]:
np.min(a,axis=0)

array([ 8, 23, 23,  7, 16])

In [123]:
# np.sum()

In [126]:
a

array([[97, 43, 43, 51, 26],
       [13, 88, 23,  7, 40],
       [49, 73, 33, 78, 45],
       [52, 79, 60, 52, 70],
       [ 8, 23, 65, 58, 16]])

In [124]:
np.sum(a)

1192

In [127]:
np.sum(a,axis=0)

array([219, 306, 224, 246, 197])

In [128]:
np.sum(a,axis=1)

array([260, 171, 278, 313, 170])

In [129]:
a

array([[97, 43, 43, 51, 26],
       [13, 88, 23,  7, 40],
       [49, 73, 33, 78, 45],
       [52, 79, 60, 52, 70],
       [ 8, 23, 65, 58, 16]])

In [131]:
a.min(axis = 0)

array([ 8, 23, 23,  7, 16])

In [133]:
a.sum(axis=0)

array([219, 306, 224, 246, 197])

In [134]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [135]:
np.min(a)

1

In [136]:
np.max(a)

27

In [151]:
a = np.random.randint(1,500,(3,3,3))
a

array([[[259, 104,  21],
        [462, 324,  59],
        [252, 434,  97]],

       [[ 14, 256, 198],
        [249, 474, 242],
        [413, 475, 188]],

       [[487, 330, 479],
        [317, 156, 219],
        [414, 186, 243]]])

In [153]:
# [[487,330,479],
#  [462,474,242],
# [414,475,243]]

In [142]:
np.min(a)

1

In [143]:
np.max(a)

498

In [147]:
np.min(a,axis=2)

array([[155, 148, 251],
       [ 33, 316, 321],
       [  8,  22,   1]])

In [148]:
# 0,1  :- col,row
# 0,1,2:- col,row

In [149]:
np.min(a,axis=1)

array([[251, 148, 155],
       [311,  33, 310],
       [ 71,   1,   8]])

In [152]:
np.min(a,axis=0)

array([[ 14, 104,  21],
       [249, 156,  59],
       [252, 186,  97]])

In [154]:
np.max(a,axis=0)

array([[487, 330, 479],
       [462, 474, 242],
       [414, 475, 243]])

In [1]:
# np.argmax()
# np.argmin()
# Iteration Array
# np.nditer()
# np.ndenumerate()
# np.concatenate
# np.stack
# slicing and assignment

# New day

In [2]:
import numpy as np

In [21]:
np.random.seed(100)
a = np.random.randint(1,100,(5,5))
a

array([[ 9, 25, 68, 88, 80],
       [49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35],
       [25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28]])

In [7]:
import random
# random.randint(1,100,(5,5))|

In [22]:
np.max(a)

99

In [23]:
np.argmax(a)

9

In [24]:
np.min(a)

3

In [25]:
np.argmin(a)

23

In [26]:
np.min(a,axis = 0)

array([ 9, 11, 61,  3, 17])

In [27]:
np.argmin(a,axis=0)

array([0, 1, 3, 4, 3], dtype=int64)

In [28]:
a

array([[ 9, 25, 68, 88, 80],
       [49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35],
       [25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28]])

In [29]:
np.min(a,axis=1)

array([ 9, 11, 15, 16,  3])

In [30]:
np.argmin(a,axis=1)

array([0, 1, 3, 1, 3], dtype=int64)

In [38]:
a = np.random.randint(1,100,(3,5,5))
# a.ndim
a

array([[[75, 73, 28, 23, 20],
        [79, 37, 59, 32, 93],
        [75,  8, 46, 67, 78],
        [38,  1, 68, 38, 58],
        [96, 17, 45, 48, 98]],

       [[14, 78, 49, 11, 25],
        [42, 18,  5, 70, 56],
        [ 6, 72, 85, 76, 37],
        [73, 42, 65,  4, 99],
        [41, 25, 32,  4, 30]],

       [[41, 15, 94, 32, 77],
        [11, 51, 31,  5, 64],
        [33,  1, 11, 66, 31],
        [ 2, 30, 31, 89, 51],
        [ 8, 65, 22, 57, 24]]])

In [39]:
np.min(a,axis=0)

array([[14, 15, 28, 11, 20],
       [11, 18,  5,  5, 56],
       [ 6,  1, 11, 66, 31],
       [ 2,  1, 31,  4, 51],
       [ 8, 17, 22,  4, 24]])

In [40]:
np.argmin(a,axis=0)

array([[1, 2, 0, 1, 0],
       [2, 1, 1, 2, 1],
       [1, 2, 2, 2, 2],
       [2, 0, 2, 1, 2],
       [2, 0, 2, 1, 2]], dtype=int64)

In [41]:
#  Iteration Array

In [42]:
# np.nditer()
# np.ndenumerate()

In [45]:
a = np.random.randint(1,100,10)
print(a)

[87 33 41 15  5 19 24 78 22 47]


In [46]:
for i in a:
    print(i)

87
33
41
15
5
19
24
78
22
47


In [49]:
a = np.random.randint(1,100,(2,2))
# print(a)



for i in a:
    print(i)

[19 51]
[48 41]


In [50]:
a = np.random.randint(1,100,(3,3,3))
print(a)




[[[98 26 93]
  [19 78 80]
  [43 10 81]]

 [[63 54 93]
  [56 15 11]
  [69 92 84]]

 [[21 88 23]
  [ 2  9 59]
  [69 98 53]]]


In [52]:
for i in a:
    print(i)
    print('---------')

[[98 26 93]
 [19 78 80]
 [43 10 81]]
---------
[[63 54 93]
 [56 15 11]
 [69 92 84]]
---------
[[21 88 23]
 [ 2  9 59]
 [69 98 53]]
---------


In [55]:
for i in a:
    for j in i:
        for k in j:
            print(k)

98
26
93
19
78
80
43
10
81
63
54
93
56
15
11
69
92
84
21
88
23
2
9
59
69
98
53


In [56]:
# np.nditer()

In [57]:
a

array([[[98, 26, 93],
        [19, 78, 80],
        [43, 10, 81]],

       [[63, 54, 93],
        [56, 15, 11],
        [69, 92, 84]],

       [[21, 88, 23],
        [ 2,  9, 59],
        [69, 98, 53]]])

In [62]:
for i in np.array(np.nditer(a)):
    print(i)

98
26
93
19
78
80
43
10
81
63
54
93
56
15
11
69
92
84
21
88
23
2
9
59
69
98
53


In [63]:
for i in np.nditer(a):
    print(i)

98
26
93
19
78
80
43
10
81
63
54
93
56
15
11
69
92
84
21
88
23
2
9
59
69
98
53


In [68]:
data = np.nditer(a)

In [74]:
next(data)

array(78)

In [77]:
for index,array in enumerate(a):
    print(index,array)
    
    print('------------')

0 [[98 26 93]
 [19 78 80]
 [43 10 81]]
------------
1 [[63 54 93]
 [56 15 11]
 [69 92 84]]
------------
2 [[21 88 23]
 [ 2  9 59]
 [69 98 53]]
------------


In [79]:
a

array([[[98, 26, 93],
        [19, 78, 80],
        [43, 10, 81]],

       [[63, 54, 93],
        [56, 15, 11],
        [69, 92, 84]],

       [[21, 88, 23],
        [ 2,  9, 59],
        [69, 98, 53]]])

In [78]:
for index,value in np.ndenumerate(a):
    print(index,value)

(0, 0, 0) 98
(0, 0, 1) 26
(0, 0, 2) 93
(0, 1, 0) 19
(0, 1, 1) 78
(0, 1, 2) 80
(0, 2, 0) 43
(0, 2, 1) 10
(0, 2, 2) 81
(1, 0, 0) 63
(1, 0, 1) 54
(1, 0, 2) 93
(1, 1, 0) 56
(1, 1, 1) 15
(1, 1, 2) 11
(1, 2, 0) 69
(1, 2, 1) 92
(1, 2, 2) 84
(2, 0, 0) 21
(2, 0, 1) 88
(2, 0, 2) 23
(2, 1, 0) 2
(2, 1, 1) 9
(2, 1, 2) 59
(2, 2, 0) 69
(2, 2, 1) 98
(2, 2, 2) 53


In [80]:
for index,value in np.ndenumerate(a):
    print(value)

98
26
93
19
78
80
43
10
81
63
54
93
56
15
11
69
92
84
21
88
23
2
9
59
69
98
53


In [81]:
a = np.random.randint(1,1000,(3,3,3,3,3))
a.ndim

5

In [83]:
for index,value in np.ndenumerate(a):
    print(index,value)

(0, 0, 0, 0, 0) 970
(0, 0, 0, 0, 1) 32
(0, 0, 0, 0, 2) 4
(0, 0, 0, 1, 0) 108
(0, 0, 0, 1, 1) 779
(0, 0, 0, 1, 2) 386
(0, 0, 0, 2, 0) 978
(0, 0, 0, 2, 1) 134
(0, 0, 0, 2, 2) 143
(0, 0, 1, 0, 0) 913
(0, 0, 1, 0, 1) 575
(0, 0, 1, 0, 2) 358
(0, 0, 1, 1, 0) 939
(0, 0, 1, 1, 1) 152
(0, 0, 1, 1, 2) 384
(0, 0, 1, 2, 0) 164
(0, 0, 1, 2, 1) 812
(0, 0, 1, 2, 2) 880
(0, 0, 2, 0, 0) 998
(0, 0, 2, 0, 1) 52
(0, 0, 2, 0, 2) 788
(0, 0, 2, 1, 0) 724
(0, 0, 2, 1, 1) 992
(0, 0, 2, 1, 2) 512
(0, 0, 2, 2, 0) 702
(0, 0, 2, 2, 1) 216
(0, 0, 2, 2, 2) 478
(0, 1, 0, 0, 0) 496
(0, 1, 0, 0, 1) 437
(0, 1, 0, 0, 2) 653
(0, 1, 0, 1, 0) 12
(0, 1, 0, 1, 1) 748
(0, 1, 0, 1, 2) 21
(0, 1, 0, 2, 0) 104
(0, 1, 0, 2, 1) 398
(0, 1, 0, 2, 2) 513
(0, 1, 1, 0, 0) 235
(0, 1, 1, 0, 1) 200
(0, 1, 1, 0, 2) 364
(0, 1, 1, 1, 0) 27
(0, 1, 1, 1, 1) 611
(0, 1, 1, 1, 2) 803
(0, 1, 1, 2, 0) 459
(0, 1, 1, 2, 1) 4
(0, 1, 1, 2, 2) 225
(0, 1, 2, 0, 0) 314
(0, 1, 2, 0, 1) 61
(0, 1, 2, 0, 2) 605
(0, 1, 2, 1, 0) 507
(0, 1, 2, 1, 1) 374
(0, 1, 2, 

In [84]:
a

array([[[[[970,  32,   4],
          [108, 779, 386],
          [978, 134, 143]],

         [[913, 575, 358],
          [939, 152, 384],
          [164, 812, 880]],

         [[998,  52, 788],
          [724, 992, 512],
          [702, 216, 478]]],


        [[[496, 437, 653],
          [ 12, 748,  21],
          [104, 398, 513]],

         [[235, 200, 364],
          [ 27, 611, 803],
          [459,   4, 225]],

         [[314,  61, 605],
          [507, 374, 737],
          [541, 718, 178]]],


        [[[330, 116,  36],
          [999, 665, 992],
          [840, 940, 528]],

         [[945, 273, 150],
          [402, 517, 865],
          [645, 539, 177]],

         [[993,  25, 568],
          [390, 819, 149],
          [ 58, 508, 169]]]],



       [[[[268, 867, 272],
          [569, 150, 626],
          [389, 837, 406]],

         [[530,  64, 608],
          [609, 649, 743],
          [263, 155, 751]],

         [[ 23, 670,  79],
          [761, 503, 259],
          [992, 845, 207]

In [86]:
a[0][0][1][0][0] = 9000

In [87]:
a

array([[[[[ 970,   32,    4],
          [ 108,  779,  386],
          [ 978,  134,  143]],

         [[9000,  575,  358],
          [ 939,  152,  384],
          [ 164,  812,  880]],

         [[ 998,   52,  788],
          [ 724,  992,  512],
          [ 702,  216,  478]]],


        [[[ 496,  437,  653],
          [  12,  748,   21],
          [ 104,  398,  513]],

         [[ 235,  200,  364],
          [  27,  611,  803],
          [ 459,    4,  225]],

         [[ 314,   61,  605],
          [ 507,  374,  737],
          [ 541,  718,  178]]],


        [[[ 330,  116,   36],
          [ 999,  665,  992],
          [ 840,  940,  528]],

         [[ 945,  273,  150],
          [ 402,  517,  865],
          [ 645,  539,  177]],

         [[ 993,   25,  568],
          [ 390,  819,  149],
          [  58,  508,  169]]]],



       [[[[ 268,  867,  272],
          [ 569,  150,  626],
          [ 389,  837,  406]],

         [[ 530,   64,  608],
          [ 609,  649,  743],
          [ 

In [88]:
a = np.random.randint(1,100,(3,3))
a

array([[95, 18, 46],
       [57, 43, 57],
       [ 2, 70, 22]])

In [90]:
a[1][2] = 600

In [91]:
print(a)

[[ 95  18  46]
 [ 57  43 600]
 [  2  70  22]]


In [94]:
a[-1][1] = 900

In [95]:
a

array([[ 95,  18,  46],
       [ 57,  43, 600],
       [  2, 900,  22]])

In [98]:
a[2][1]

900

In [99]:
a = np.random.randint(1,100,(3,3,3))
a

array([[[76, 32, 57],
        [77, 83, 36],
        [ 5, 98, 72]],

       [[47, 85, 15],
        [44, 91, 39],
        [16, 25, 57]],

       [[54, 97, 82],
        [65, 13, 66],
        [23, 51, 17]]])

In [101]:
a[1][1][1] = 9000

In [102]:
a

array([[[  76,   32,   57],
        [  77,   83,   36],
        [   5,   98,   72]],

       [[  47,   85,   15],
        [  44, 9000,   39],
        [  16,   25,   57]],

       [[  54,   97,   82],
        [  65,   13,   66],
        [  23,   51,   17]]])

In [104]:
a[2][2][2]+= 10

In [105]:
a

array([[[  76,   32,   57],
        [  77,   83,   36],
        [   5,   98,   72]],

       [[  47,   85,   15],
        [  44, 9000,   39],
        [  16,   25,   57]],

       [[  54,   97,   82],
        [  65,   13,   66],
        [  23,   51,   27]]])

In [107]:
a[0][1][0] = 700

In [108]:
a

array([[[  76,   32,   57],
        [ 700,   83,   36],
        [   5,   98,   72]],

       [[  47,   85,   15],
        [  44, 9000,   39],
        [  16,   25,   57]],

       [[  54,   97,   82],
        [  65,   13,   66],
        [  23,   51,   27]]])

In [109]:
# a[0][1][0]

# a[arr,row,col]

In [111]:
a[0,1,0] = 800

In [112]:
a

array([[[  76,   32,   57],
        [ 800,   83,   36],
        [   5,   98,   72]],

       [[  47,   85,   15],
        [  44, 9000,   39],
        [  16,   25,   57]],

       [[  54,   97,   82],
        [  65,   13,   66],
        [  23,   51,   27]]])

In [114]:
a[1,1,2] = 200

In [115]:
a

array([[[  76,   32,   57],
        [ 800,   83,   36],
        [   5,   98,   72]],

       [[  47,   85,   15],
        [  44, 9000,  200],
        [  16,   25,   57]],

       [[  54,   97,   82],
        [  65,   13,   66],
        [  23,   51,   27]]])

In [116]:
a = np.random.randint(1,100,(2,2,3,3))
a

array([[[[89,  3, 58],
         [ 8, 82, 95],
         [89, 24, 13]],

        [[29,  2, 91],
         [83, 62, 19],
         [93,  4, 48]]],


       [[[27, 29, 82],
         [32, 84, 97],
         [39, 29, 86]],

        [[58,  4,  9],
         [18, 61, 52],
         [59, 75, 68]]]])

In [118]:
# a[arr2,arr1,row,col]

a[0][1][1][2] = 100

In [119]:
a

array([[[[ 89,   3,  58],
         [  8,  82,  95],
         [ 89,  24,  13]],

        [[ 29,   2,  91],
         [ 83,  62, 100],
         [ 93,   4,  48]]],


       [[[ 27,  29,  82],
         [ 32,  84,  97],
         [ 39,  29,  86]],

        [[ 58,   4,   9],
         [ 18,  61,  52],
         [ 59,  75,  68]]]])

In [121]:
a[1,1,1,0] = 100

In [122]:
a

array([[[[ 89,   3,  58],
         [  8,  82,  95],
         [ 89,  24,  13]],

        [[ 29,   2,  91],
         [ 83,  62, 100],
         [ 93,   4,  48]]],


       [[[ 27,  29,  82],
         [ 32,  84,  97],
         [ 39,  29,  86]],

        [[ 58,   4,   9],
         [100,  61,  52],
         [ 59,  75,  68]]]])

In [124]:
a = np.random.randint(1,100,(5,5))
a

array([[83, 26,  1, 31, 38],
       [99, 68,  7, 97, 24],
       [73, 74, 47, 81, 47],
       [29, 98,  9,  2, 48],
       [29, 16,  6, 79, 89]])

In [125]:
# slicing

# a[r,c]

# a[s:s:s,s:s:s]

# a[arr,r,c]

# a[s:s:s,s:s:s,s:s:s]

In [129]:
a[1,1:4]

array([68,  7, 97])

In [130]:
a[1,1:4] = [1,1,1]

In [131]:
a

array([[83, 26,  1, 31, 38],
       [99,  1,  1,  1, 24],
       [73, 74, 47, 81, 47],
       [29, 98,  9,  2, 48],
       [29, 16,  6, 79, 89]])

In [132]:
a[1:4,2]

array([ 1, 47,  9])

In [133]:
a[1:4,2] = [0]*3

In [134]:
a

array([[83, 26,  1, 31, 38],
       [99,  1,  0,  1, 24],
       [73, 74,  0, 81, 47],
       [29, 98,  0,  2, 48],
       [29, 16,  6, 79, 89]])

In [137]:
a[1:4,1:4] = 0

In [138]:
a[1:4,1:4] 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [139]:
a

array([[83, 26,  1, 31, 38],
       [99,  0,  0,  0, 24],
       [73,  0,  0,  0, 47],
       [29,  0,  0,  0, 48],
       [29, 16,  6, 79, 89]])

In [141]:
a[::4,::4]

array([[83, 38],
       [29, 89]])

In [144]:
a = a.astype(str)

In [145]:
a[::4,::4] = 'Majid'

In [147]:
print(a)

[['Majid' '26' '1' '31' 'Majid']
 ['99' '0' '0' '0' '24']
 ['73' '0' '0' '0' '47']
 ['29' '0' '0' '0' '48']
 ['Majid' '16' '6' '79' 'Majid']]


In [148]:
a = np.random.randint(1,100,(3,3,3))
a

array([[[69, 62, 16],
        [11, 90, 40],
        [38, 86, 74]],

       [[82, 11, 96],
        [93, 38, 45],
        [73, 54, 92]],

       [[76, 12, 69],
        [35, 28, 76],
        [25, 47, 34]]])

In [151]:
a[1,:,:]

array([[82, 11, 96],
       [93, 38, 45],
       [73, 54, 92]])

In [153]:
a[1] = 0

In [154]:
a

array([[[69, 62, 16],
        [11, 90, 40],
        [38, 86, 74]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[76, 12, 69],
        [35, 28, 76],
        [25, 47, 34]]])

In [156]:
a[2,1:,1:] = 0

In [157]:
a

array([[[69, 62, 16],
        [11, 90, 40],
        [38, 86, 74]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[76, 12, 69],
        [35,  0,  0],
        [25,  0,  0]]])

In [161]:
a[0,0,0:2] = 0

In [163]:
a[0,2,1:] = 0

In [164]:
a

array([[[ 0,  0, 16],
        [11, 90, 40],
        [38,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[76, 12, 69],
        [35,  0,  0],
        [25,  0,  0]]])

In [170]:
a[0,[0,2],[1,2]]

array([0, 0])

In [171]:
a = np.random.randint(1,100,(3,3,3))
a

array([[[47, 44, 51],
        [62, 43, 41],
        [61,  5, 31]],

       [[51, 52, 80],
        [40, 75,  4],
        [ 3, 88, 48]],

       [[26, 19, 37],
        [63, 19, 99],
        [90, 88, 59]]])

In [172]:
a[:,0,0::2]

array([[47, 51],
       [51, 80],
       [26, 37]])

In [174]:
a[:,0,[0,2]] = 100

In [175]:
a

array([[[100,  44, 100],
        [ 62,  43,  41],
        [ 61,   5,  31]],

       [[100,  52, 100],
        [ 40,  75,   4],
        [  3,  88,  48]],

       [[100,  19, 100],
        [ 63,  19,  99],
        [ 90,  88,  59]]])