In [1]:
# # DA:-Data Analyst:- Designation:-

# # Python:- More than 

# # after func:- DA

# # Python:- Module:- Numpy, Pandas, Seaborn, Matplotlib

# # Basic, Python:- R:- 7 days:- 10-12 hrs

# Data:- databases/Files:- Python
        
# powerBI:- No Code
    
    
    
# python:
    
# # numpy:- numerical Python:- 


# a = [1,243,45,456]

# b = [1,234,56,67]




In [6]:
a = [1,2,45,456]

b = [1,20,56,67]

c = []
for i,j in enumerate(a):
    for k,l in enumerate(b):
        if i == k:
            c.append(j*l)
print(c)

[1, 40, 2520, 30552]


In [10]:
import numpy as np

a = np.array([1,2,45,456])

b = np.array([1,20,56,67])


a*b

array([    1,    40,  2520, 30552])

In [14]:
# numpy:- 12% for DA
# numy ML:- 40%
# numpy AI:- 50%
    
# pandas:- Excel in Python:- pannel dataframe:- 
            
# dataframe:- tabular structure:- table:- rows/columns

# column
# data mainuplation
# data + data

# data:- no limit
    
    
# c- language
# python:- c language


# Pandas:- 60%:- 
# matplotlib:- 10%
# seaborn:- 10%
# stats & Excel:- 10%
# sql:- 40%

# Excel;- 60%

# powerbi:- DA;- 20%

# Powerbi developer:- 60%
# sql:- 40
# python:- 10-20 
# Excel
# story telling
# ui:- easy:- microsoft:- easy integration:- DAX:- python, R
# tableau:- Complex  DAX


# Aws:- Quicksight


# cloud:- Aws, GCP, Azure

In [15]:
# numpy:- 12%

# plotly:- Advance visual libraries in python

In [16]:
# numpy:- numerical python

In [17]:
a = [1,2,45,456]

b = [1,20,56,67]

a + b

[1, 2, 45, 456, 1, 20, 56, 67]

In [18]:
# array:- n dimesional data
# 1d array
# 2d array
# 3d array
# 4d array
# 5d array
# nd array

In [19]:
a = [1,233,5,6]

arr_a = np.array(a)

print(a)
print(arr_a)

[1, 233, 5, 6]
[  1 233   5   6]


In [20]:
a = ['1','233',5,6]

arr_a = np.array(a)

print(a)
print(arr_a)

['1', '233', 5, 6]
['1' '233' '5' '6']


In [22]:
# list:- can contain multiple data type
# array:- can contain only one data type at a time

In [23]:
a = [23.6,5,6]

arr_a = np.array(a)

print(a)
print(arr_a)

[23.6, 5, 6]
[23.6  5.   6. ]


In [24]:
arr_a.dtype

dtype('float64')

In [ ]:
16,32,64,128

In [26]:
arr_b = arr_a.astype('float16')

In [27]:
arr_a.dtype

dtype('float64')

In [28]:
arr_b.dtype

dtype('float16')

In [29]:
arr_a

array([23.6,  5. ,  6. ])

In [30]:
arr_b

array([23.6,  5. ,  6. ], dtype=float16)

In [31]:
arr_2d = np.array([1,23,25])

arr_2d.ndim

1

In [32]:
arr_2d = np.array([[1,23,25]])

arr_2d.ndim

2

In [33]:
arr_3d = np.array([[[1,23,25]]])

arr_3d.ndim

3

In [34]:
name = 'jatin'


print('hello',name,'How are you?')

hello jatin How are you?


In [36]:
print(f'hello {name} How are you?')

hello jatin How are you?


In [39]:
a = [1,243,454,2134,36,578]
a.sort(reverse=True)
a[:3]

[2134, 578, 454]